/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyVoiceRouteImport } from './routes/journey.voice'
import { Route as JourneyVideosRouteImport } from './routes/journey.videos'
import { Route as JourneyTestRouteImport } from './routes/journey.test'
import { Route as JourneyOvertsRouteImport } from './routes/journey.overts'
import { Route as JourneyGratitudeRouteImport } from './routes/journey.gratitude'
import { Route as JourneyGoalsRouteImport } from './routes/journey.goals'
import { Route as JourneyAudioRouteImport } from './routes/journey.audio'
import { Route as AdminUserUserIdRouteImport } from './routes/admin.user.$userId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyVoiceRoute = JourneyVoiceRouteImport.update({
  id: '/journey/voice',
  path: '/journey/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyVideosRoute = JourneyVideosRouteImport.update({
  id: '/journey/videos',
  path: '/journey/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyTestRoute = JourneyTestRouteImport.update({
  id: '/journey/test',
  path: '/journey/test',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyOvertsRoute = JourneyOvertsRouteImport.update({
  id: '/journey/overts',
  path: '/journey/overts',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGratitudeRoute = JourneyGratitudeRouteImport.update({
  id: '/journey/gratitude',
  path: '/journey/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGoalsRoute = JourneyGoalsRouteImport.update({
  id: '/journey/goals',
  path: '/journey/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyAudioRoute = JourneyAudioRouteImport.update({
  id: '/journey/audio',
  path: '/journey/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/journey/audio': typeof JourneyAudioRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/gratitude': typeof JourneyGratitudeRoute
  '/journey/overts': typeof JourneyOvertsRoute
  '/journey/test': typeof JourneyTestRoute
  '/journey/videos': typeof JourneyVideosRoute
  '/journey/voice': typeof JourneyVoiceRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/journey/audio': typeof JourneyAudioRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/gratitude': typeof JourneyGratitudeRoute
  '/journey/overts': typeof JourneyOvertsRoute
  '/journey/test': typeof JourneyTestRoute
  '/journey/videos': typeof JourneyVideosRoute
  '/journey/voice': typeof JourneyVoiceRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/journey/audio': typeof JourneyAudioRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/gratitude': typeof JourneyGratitudeRoute
  '/journey/overts': typeof JourneyOvertsRoute
  '/journey/test': typeof JourneyTestRoute
  '/journey/videos': typeof JourneyVideosRoute
  '/journey/voice': typeof JourneyVoiceRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/journey/audio'
    | '/journey/goals'
    | '/journey/gratitude'
    | '/journey/overts'
    | '/journey/test'
    | '/journey/videos'
    | '/journey/voice'
    | '/admin/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/journey/audio'
    | '/journey/goals'
    | '/journey/gratitude'
    | '/journey/overts'
    | '/journey/test'
    | '/journey/videos'
    | '/journey/voice'
    | '/admin/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/journey/audio'
    | '/journey/goals'
    | '/journey/gratitude'
    | '/journey/overts'
    | '/journey/test'
    | '/journey/videos'
    | '/journey/voice'
    | '/admin/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  JourneyAudioRoute: typeof JourneyAudioRoute
  JourneyGoalsRoute: typeof JourneyGoalsRoute
  JourneyGratitudeRoute: typeof JourneyGratitudeRoute
  JourneyOvertsRoute: typeof JourneyOvertsRoute
  JourneyTestRoute: typeof JourneyTestRoute
  JourneyVideosRoute: typeof JourneyVideosRoute
  JourneyVoiceRoute: typeof JourneyVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/voice': {
      id: '/journey/voice'
      path: '/journey/voice'
      fullPath: '/journey/voice'
      preLoaderRoute: typeof JourneyVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/videos': {
      id: '/journey/videos'
      path: '/journey/videos'
      fullPath: '/journey/videos'
      preLoaderRoute: typeof JourneyVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/test': {
      id: '/journey/test'
      path: '/journey/test'
      fullPath: '/journey/test'
      preLoaderRoute: typeof JourneyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/overts': {
      id: '/journey/overts'
      path: '/journey/overts'
      fullPath: '/journey/overts'
      preLoaderRoute: typeof JourneyOvertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/gratitude': {
      id: '/journey/gratitude'
      path: '/journey/gratitude'
      fullPath: '/journey/gratitude'
      preLoaderRoute: typeof JourneyGratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/goals': {
      id: '/journey/goals'
      path: '/journey/goals'
      fullPath: '/journey/goals'
      preLoaderRoute: typeof JourneyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/audio': {
      id: '/journey/audio'
      path: '/journey/audio'
      fullPath: '/journey/audio'
      preLoaderRoute: typeof JourneyAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  JourneyAudioRoute: JourneyAudioRoute,
  JourneyGoalsRoute: JourneyGoalsRoute,
  JourneyGratitudeRoute: JourneyGratitudeRoute,
  JourneyOvertsRoute: JourneyOvertsRoute,
  JourneyTestRoute: JourneyTestRoute,
  JourneyVideosRoute: JourneyVideosRoute,
  JourneyVoiceRoute: JourneyVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
